name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
    - '**/*.md'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 15 * * 0'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          max-allowed-issues: 2147483647
          # Example: Specify rules for eslint
          eslint:
            enabled: true
            configuration:
              rules:
                - no-console: "warn"
                - no-unused-vars: "error"
          # Example: Specify rules for spotbugs
          spotbugs:
            enabled: true
            configuration:
              rules:
                - DeadStore: "true"
                - UnusedImport: "true"

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
