name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
      - name: Run Tests
        run: |
          pytest --cov=my_project tests/
      - name: Upload Coverage to Codacy
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
