name: Documentation Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install Dependencies
        run: npm install
      - name: Generate docs
        run: npm run docs