name: Main Workflow

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '24 15 * * 0'

jobs:

  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.ref_name }}
      - name: Install Dependencies
        run: npm install
      - name: Generate docs
        run: npm run docs
      - name: Copy generated docs
        run: cp -R jsdocsgenerated/* docs
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git commit -m "Generated JSDocs"
          git push
