name: JSDocs

on: {pull_request}

jobs:
  Generate Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run docs
