name: Linting

on: {pull_request}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint:check
      - name: Fixing
        run: npm run lint:fix
