name: Linting

on:
  workflow_run:
    workflows: ["Codacy Security Scan"]
    types:
      - completed

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint:check
      - name: Fixing
        run: npm run lint:fix
