name: Main Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
    - '**/*.md'
    - 'jsdocsgenerated/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 15 * * 0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint:check

  testing:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Set up Xvfb
        uses: GabrielBB/xvfb-action@v1.6
      - name: Start Local Server
        run: npx http-server -p 8080 &
      - name: Run Tests
        run: npm test
